# Generated by Django 5.1.7 on 2025-03-16 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_otp_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('Moderateur', 'Modérateur'), ('contributor', 'Contributeur')], default='contributor', max_length=20),
        ),
    ]
